version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nothub"
    reviewers:
      - "nothub"
    commit-message:
      prefix: "maven"
      include: "scope"

