blank_issues_enabled: false
contact_links:
  - name: "â—Exploits"
    url: https://discord.gg/papermc
    about: |
      Since GitHub doesnâ€™t currently support private issues, exploit reports are managed through our Discord.
      To report an exploit, please visit the #paper-exploit-report channel.
  - name: "ğŸ—¨ Questions"
    url: https://discord.gg/papermc
    about: If you have questions or need help with any minor issues, feel free to ask us on our Discord server!
